### ISSUE TITLE
SectioningException <-- java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Garfius** [UniTime/unitime#3]
The software is logging about a thousand times a day:

org.unitime.timetable.gwt.shared.SectioningException: 
	at org.unitime.timetable.solver.jgroups.OnlineStudentSchedulingContainer.createInstance(OnlineStudentSchedulingContainer.java:166)
	at org.unitime.timetable.solver.jgroups.OnlineStudentSchedulingContainer.createSolver(OnlineStudentSchedulingContainer.java:116)
	at org.unitime.timetable.solver.jgroups.LocalSolverServer$Updater.checkForNewServers(LocalSolverServer.java:209)
	at org.unitime.timetable.solver.jgroups.LocalSolverServer$Updater.run(LocalSolverServer.java:159)
Caused by: java.lang.ClassNotFoundException: 
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at org.unitime.timetable.solver.jgroups.OnlineStudentSchedulingContainer.createInstance(OnlineStudentSchedulingContainer.java:151)
	... 3 more

**Comment by tomas-muller** [comment]
Looks like you have a wrong value set in the application property named unitime.enrollment.server.class (probably a blank value). It either should not be set at all (in which case the online student scheduling solver implementation is selected automatically based on whether the replication is enabled) or set to a class implementing the org.unitime.timetable.onlinesectioning.OnlineSectioningServer interface.

Please check you custom properties file (if you have any) and/or the Administration > Defaults > Configuration page.

**Comment by Garfius** [comment]
I have a default installation, using mostly default setting with no external solvers nor ldap connection.

So, i have found timetable.jar\org\unitime\timetable\onlinesectioning within webapps/ROOT/WEB-INF/lib/timetable.jar

What shall i have to do?

Also, thanks for the fast response and analisys.

**Comment by tomas-muller** [comment]
Go to the Administration > Defaults > Configuration page and check for the `unitime.enrollment.server.class` property while "Show all properties" toggle at the bottom of the screen is not checked. If you see the property there, click on it and hit the Delete button. If the Delete button is not there, go to your custom properties file (if you have created one) and look for a line like this:

```
unitime.enrollment.server.class=
```

If you see such line in there, delete it (or comment it out).

If this does not help, set the property to `org.unitime.timetable.onlinesectioning.server.InMemoryServer` using the Application Configuration page mentioned earlier, or in the configuration file:

```
unitime.enrollment.server.class=org.unitime.timetable.onlinesectioning.server.InMemoryServer
```

**Comment by Garfius** [comment]
Seems to work good.

Thanks !
