### ISSUE TITLE
Error in ANT build 

### ISSUE THREAD

**Issue by KarthikRv93** [UniTime/unitime#49]
The UniTime application source code was working fine in my local.
Since 2 days I am getting this error without any code change :
SEVERE: Error configuring application listener of class org.springframework.web.context.ContextLoaderListener
java.lang.ClassNotFoundException: org.springframework.web.context.ContextLoaderListener
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1955)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1798)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:536)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:518)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:148)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5113)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5720)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

If anyone has faced a similar issue please let me know how to resolve it?

**Comment by tomas-muller** [comment]
The message indicates that you are missing the spring-web-xxx.jar library. Is it present in the UniTime.war, WEB-INF/lib folder)?

I sometimes get this (or similar) error when I am running tomcat and deploying UniTime within eclipse ([see here](http://help.unitime.org/eclipse)). What seems to work for me is to

- un-deploy UniTime and restart the tomcat (on the Servers tab, remove the UniTime web module; also make sure that webapps/UniTime is deleted)
- stop the tomcat, deploy UniTime again, and start the tomcat

Everything is usually back to normal after this.
