### ISSUE TITLE
Attribute value ApplicationProperties.getProperty("tmtbl.header.external") is quoted with " which must be escaped when used within the value]

### ISSUE THREAD

**Issue by RichardChambula** [UniTime/unitime#8]
Hello, I have recently installed/configured UniTime. When I load it in the browser, I am not getting the login screen, it's basically just blank.
According to my log file:

SEVERE: Servlet.service() for servlet [jsp] in context with path [/UniTime] threw exception [/index.jsp (line: 30, column: 38) Attribute value ApplicationProperties.getProperty("tmtbl.header.external") is quoted with " which must be escaped when used within the value] with root cause
org.apache.jasper.JasperException: /index.jsp (line: 30, column: 38) Attribute value ApplicationProperties.getProperty("tmtbl.header.external") is quoted with " which must be escaped when used within the value
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:89)
	at org.apache.jasper.compiler.Parser.parseAttributeValue(Parser.java:285)
	at org.apache.jasper.compiler.Parser.parseAttribute(Parser.java:234)
	at org.apache.jasper.compiler.Parser.parseAttributes(Parser.java:162)
	at org.apache.jasper.compiler.Parser.parseAttributes(Parser.java:153)
	at org.apache.jasper.compiler.Parser.parseInclude(Parser.java:838)
	at org.apache.jasper.compiler.Parser.parseStandardAction(Parser.java:1105)
	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1441)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:138)
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:102)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.HibSessionFilter.doFilter(HibSessionFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by tomas-muller** [comment]
What version of UniTime are you trying to use? This looks like a strict quote escaping issue that occurred due to a change in Tomcat (see [Bug 45015](https://bz.apache.org/bugzilla/show_bug.cgi?id=45015)) and that was corrected in UniTime by commit 00afbe5 (back in October 2008, fixing UniTime 3.1 at that time).

**Comment by tomas-muller** [comment]
It turned out the issue has been reported on UniTime 3.1 build 101 (built September 5, 2008). The problem has been fixed by commit 00afbe5 long time ago.

**Comment by athena007** [comment]
Tomas i sent you an email concerning paid support. Could u kindly confirm
receipt. Thanks Kofi
